# -*- coding: utf-8 -*-
"""Datacollection&API in ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XatQAX7yKnd75na_T-Tu2AP5Bk2Wvlcw

DATA COLLECTION: can be done in 3 ways

1.kaggle

2.UCI ML repo

3.Google dataset search
"""

import pandas as pd

#loading dataset to dataframe
dataset=pd.read_csv('/content/boston.csv')

dataset.head()

dataset.shape

"""API- Application Programming Interface

Software intermediaries in this case transferring data from kaggle to colab
"""

#installing a kaggle library
!pip install kaggle

"""UPLOAD your kaggle.json(same google account)"""

#configuring the path of kaggle.json
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

"""importing the earthquake dataset"""

#Api to fetch dataset from kaggle
!kaggle competitions download -c LANL-Earthquake-Prediction

#extracting compressed dataset
from zipfile import ZipFile
dataset= '/content/LANL-Earthquake-Prediction.zip'
with ZipFile(dataset,'r') as zip:
  zip.extractall()
  print('dataset is extracted')

