# -*- coding: utf-8 -*-
"""Label Encoding.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17aSssBQfrVGm9TwJhDDDN27hOEMSEfbJ

#label encoding
Converting labels into numeric form
used in classification
"""

import pandas as pd
from sklearn.preprocessing import LabelEncoder

"""Label encoding of breast cancer data set"""

cancer_data=pd.read_csv('/content/data.csv')

cancer_data.head()

cancer_data.tail()

#finding the count of different labels
cancer_data['diagnosis'].value_counts()

#load the label encoder
label_encode= LabelEncoder()

labels=label_encode.fit_transform(cancer_data.diagnosis)

#appending data to the dataframe
cancer_data['target']=labels

cancer_data.head()

"""0 ---> benign
1 ---> Malignant(safe)
"""

cancer_data['target'].value_counts()

"""label encoding is done on the basis for alphabetically"""

iris_data=pd.read_csv('/content/iris_data.csv')

iris_data.head()

iris_data.shape

iris_data['Species'].value_counts()

label_encode1=LabelEncoder()

iris_labels = label_encode1.fit_transform(iris_data.Species)

iris_data['target']=iris_labels

iris_data.head()

iris_data['target'].value_counts()

"""Iris-setosa----> 0

Iris-versicolor ----> 1

Iris-verginica ----> 2
"""

