# -*- coding: utf-8 -*-
"""Numpy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ebeuAxpehmVGjEFPs1eXK-8kUZw00E5X
"""



"""#Numpy

"""

a=[1,'m',3,'r']

print(a)

a.append("v")

del a[2]

print(a)

import numpy as np

"""List vs numpy time taken"""

from time import process_time

"""time taken by list"""

py_list=[i for i in range(100000)]

start_time= process_time()

py_list=[i+5 for i in py_list]

end_time=process_time()

print(end_time - start_time)

np_arr= np.array([ i for i in range(100000)])
start_time= process_time()

np_arr += 5

end_time=process_time()

print(end_time - start_time)

"""Numpy arrays"""

np_arr=np.array([1,2,3,4])
print(np_arr)

type(np_arr)

"""to show dimension"""

np_arr.shape

"""Multidimensional array"""

b=np.array([(1,2,3),(4,5,6),(7,8,9)])

print(b)
type(b)
b.shape

c=np.array([(1,2,3),(4,5,6)],dtype=float)

print(c)

"""Initial placeholders in numpy array"""

#creating an array of 0s
d=np.zeros((3,2,4))

print(d)

y=np.ones((3,3))

print(y)

x=np.full((3,4),5)

print(x)

"""identity matrix"""

a=np.eye(4)

print(a)

"""random values"""

rand=np.random.random((3,4))

print(rand)

"""random array with integers"""

rand1=np.random.randint(1,6,(3,4))

print(rand1)

"""evenly spaced"""

e=np.linspace(10,30,5)

print(e)

f=np.arange(10,30,5)

print(f)

"""list to array"""

list1=[1,2,3,4,5]
g=np.asarray(list1)

print(g)
type(g)

"""analyse an array"""

j=np.random.randint(0,100,(5,4))
print(j)

j.shape

j.ndim

#to check no. of elements
j.size

#to check the datatype of the values
print(j.dtype)

"""mathematical operations

"""

#elementwise addition is not possible in a list but it is in an array
a=np.random.randint(0,10,(2,3))
b=np.random.randint(0,10,(2,3))
print(a)
print(b)

print(a+b)

print(np.add(a,b))

print(np.divide(a,b))

"""array manipulation"""

arr=np.random.randint(0,20,(2,3))

print(arr)

tran=np.transpose(arr)
print(tran)
print(tran.shape)

#other way to find transpose
trans2=tran.T

print(trans2)

#reshaping
a=np.random.randint(1,5,(2,3))
print(a)

b=a.reshape(3,2)

print(b)

