# -*- coding: utf-8 -*-
"""seaborn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hPMXqXK80nI-bPXI0AOh21OSIW5ASHAa

Seaborn
"""

import seaborn as sns

import matplotlib.pyplot as plt

import numpy as np
import pandas as pd

"""Note: Seaborn has some builtin datasets

"""

#total bill vs tip dataset
tips=sns.load_dataset('tips')  #this is will import it as a pandas dataset

tips.head()

#setting a theme for the plots
sns.set_theme()

#visualise data
sns.relplot(data=tips,x='total_bill',y='tip',col='time',hue='sex',style= 'smoker',size='size')

#load the iris dataset
iris=sns.load_dataset('iris')

iris.head()

"""Scatter plot to cluster different species"""

#clustering it
#hue means on what basis data will be separated
sns.scatterplot(x='sepal_length',y='petal_length',hue='species',data=iris)

sns.scatterplot(x='sepal_width',y='petal_width',hue='species',data=iris)

#loading titanic dataset
titanic=sns.load_dataset('titanic')

titanic.head()



sns.scatterplot(data=titanic,x='survived',y='pclass',hue='who')

titanic.head()

"""count plot

"""

sns.countplot(x='class',data=titanic)

sns.countplot(x='survived',hue='pclass',data=titanic)

sns.countplot(x='survived',data=titanic)

"""Bar chart"""

sns.barplot(x='sex',y='survived',hue='pclass',data=titanic)

boston=pd.read_csv('/content/BostonHousing.csv')

boston.head()

"""Distribution plot"""

sns.distplot(boston['medv'])

"""Correlation matrix"""

correlation=boston.corr()

#constructing a heat map
#firstly constructing a figure space using matplotlib
plt.figure(figsize=(10,10))
sns.heatmap(correlation,cbar=True, square=True, fmt='.1f',annot=True,annot_kws={'size':8},cmap='Blues')

